export type NzGuideCategory='Money & tax'|'Work & employment'|'Housing & household costs'|'Immigration & citizenship'|'Holidays & family'|'Jobs & careers';
export type NzGuideEntry={href:string;title:string;shortTitle:string;description:string;category:NzGuideCategory;searchTerms:string[];fresh:string;related:string[];};
export const NZ_GUIDE_SITE_URL='https://webfitnews.com';
export const nzGuideCategories:NzGuideCategory[]=['Money & tax','Work & employment','Housing & household costs','Immigration & citizenship','Holidays & family','Jobs & careers'];
export const nzGuides:NzGuideEntry[]=[
{href:'/minimum-wage',title:'Minimum Wage NZ 2026 — $23.95 Adult Rate & Calculator',shortTitle:'Minimum Wage NZ',description:'Current adult, starting-out and training minimum wage rates, 40-hour weekly pay examples, eligibility and calculator.',category:'Work & employment',searchTerms:['minimum wage nz','minimum wage nz 2026','new zealand minimum wage','minimum wage calculator nz','minimum wage 40 hours nz'],fresh:'Regular official-source checks',related:['/nz-paye-calculator','/nz-holiday-pay-calculator','/nz-leave-entitlement-calculator','/jobs-in-new-zealand']},
{href:'/nz-paye-calculator',title:'PAYE Calculator NZ 2026 — Salary, Tax & Take-Home Pay',shortTitle:'PAYE Calculator NZ',description:'Estimate income tax, ACC, KiwiSaver, student-loan deductions and New Zealand take-home pay from annual salary.',category:'Money & tax',searchTerms:['paye calculator nz','nz tax calculator','salary calculator nz','take home pay calculator nz','salary after tax nz'],fresh:'Regular IRD source checks',related:['/nz-tax-code-finder','/nz-acc-levy-calculator','/nz-kiwisaver-calculator','/nz-student-loan-calculator']},
{href:'/nz-acc-levy-calculator',title:'ACC Levy Calculator NZ 2026/27 — 1.75% Earners’ Levy',shortTitle:'ACC Levy Calculator NZ',description:'Calculate the employee ACC Earners’ levy using the current 1.75% rate, $156,641 earnings cap and $2,741.22 maximum.',category:'Money & tax',searchTerms:['acc levy calculator nz','acc levy nz','acc earners levy','acc levy rate 2026','acc maximum earnings nz'],fresh:'Daily ACC and IRD source checks',related:['/nz-paye-calculator','/minimum-wage','/nz-tax-code-finder','/jobs-in-new-zealand']},
{href:'/nz-tax-code-finder',title:'NZ Tax Code Finder 2026 — Which IRD Tax Code Should I Use?',shortTitle:'NZ Tax Code Finder',description:'Find the likely IRD tax code for a main job, second job or student loan, including M, ME, SB, S, SH, ST, SA and SL.',category:'Money & tax',searchTerms:['nz tax code finder','which tax code should i use nz','tax code nz','ird tax code','secondary tax code nz','m tax code nz'],fresh:'Regular IRD source checks',related:['/nz-paye-calculator','/nz-student-loan-calculator','/nz-kiwisaver-calculator','/minimum-wage']},
{href:'/nz-kiwisaver-calculator',title:'KiwiSaver Calculator NZ 2026 — Contributions & ESCT',shortTitle:'KiwiSaver Calculator NZ',description:'Estimate employee and employer KiwiSaver contributions, ESCT and the government contribution under current 2026 settings.',category:'Money & tax',searchTerms:['kiwisaver calculator nz','nz kiwisaver calculator','kiwisaver employer contribution','kiwisaver contribution rates 2026','esct calculator nz'],fresh:'Regular IRD source checks',related:['/nz-paye-calculator','/nz-tax-code-finder','/nz-superannuation','/nz-student-loan-calculator']},
{href:'/nz-student-loan-calculator',title:'NZ Student Loan Calculator 2026/27 — Threshold & 12% Rate',shortTitle:'NZ Student Loan Calculator',description:'Calculate student-loan deductions by pay period using the current $24,128 annual threshold and standard 12% repayment rate.',category:'Money & tax',searchTerms:['student loan calculator nz','nz student loan calculator','student loan repayment calculator nz','student loan threshold nz','student loan repayment nz'],fresh:'Regular IRD source checks',related:['/nz-paye-calculator','/nz-tax-code-finder','/nz-kiwisaver-calculator','/jobs-in-new-zealand']},
{href:'/nz-superannuation',title:'NZ Super Rates 2026 — Eligibility, Age & Residence Rules',shortTitle:'NZ Super Rates & Eligibility',description:'Check current NZ Super fortnightly rates, pension age 65, residence requirements and core eligibility.',category:'Money & tax',searchTerms:['nz super rates 2026','nz superannuation','nz super eligibility','nz pension age','new zealand pension','nz super residence requirements'],fresh:'Daily Work and Income source checks',related:['/nz-rates-rebate-calculator','/nz-tax-code-finder','/nz-citizenship','/nz-kiwisaver-calculator']},
{href:'/nz-rates-rebate-calculator',title:'Rates Rebate Calculator NZ 2026/27 — Check Your $830 Rebate',shortTitle:'Rates Rebate Calculator NZ',description:'Estimate the 2026/27 council rates rebate using rates, household income, dependants and SuperGold status.',category:'Housing & household costs',searchTerms:['rates rebate calculator nz','rates rebate nz','rates rebate 2026 2027','rates rebate income threshold','rates rebate eligibility nz','supergold rates rebate'],fresh:'Daily official-source checks',related:['/nz-superannuation','/nz-tenancy-rent-guide','/nz-paye-calculator','/nz-guides']},
{href:'/nz-tenancy-rent-guide',title:'Rent Increase NZ 2026 — 12-Month Rule, Notice & Bond',shortTitle:'Rent Increase NZ',description:'Check the 12-month rent-increase rule, 60-day notice, bond limits, periodic-tenancy notice periods and Healthy Homes obligations.',category:'Housing & household costs',searchTerms:['rent increase nz','rent increase notice nz','how often can rent increase nz','nz tenancy','tenant rights nz','bond nz tenancy'],fresh:'Daily Tenancy Services source checks',related:['/nz-rates-rebate-calculator','/public-holidays','/jobs-in-new-zealand','/nz-guides']},
{href:'/nz-holiday-pay-calculator',title:'Holiday Pay Calculator NZ 2026 — Annual Leave & Public Holiday Pay',shortTitle:'Holiday Pay Calculator NZ',description:'Calculate annual-leave pay using OWP vs AWE and estimate public-holiday time-and-a-half under current NZ rules.',category:'Work & employment',searchTerms:['holiday pay calculator nz','holiday pay nz','annual leave pay calculator nz','public holiday pay nz','time and a half nz','8 percent holiday pay nz'],fresh:'Current Employment NZ rules',related:['/nz-leave-entitlement-calculator','/public-holidays','/minimum-wage','/nz-paye-calculator']},
{href:'/nz-leave-entitlement-calculator',title:'Sick Leave NZ 2026 — 10-Day Rule & Annual Leave Calculator',shortTitle:'Sick Leave NZ & Annual Leave',description:'Check the 10-day sick-leave entitlement, 20-day carry-over limit and four-week annual holiday entitlement.',category:'Work & employment',searchTerms:['sick leave nz','sick leave calculator nz','10 days sick leave nz','annual leave calculator nz','annual leave entitlement nz'],fresh:'Daily Employment NZ source checks',related:['/nz-holiday-pay-calculator','/minimum-wage','/public-holidays','/jobs-in-new-zealand']},
{href:'/public-holidays',title:'Public Holidays NZ 2026 & 2027 — Dates & Observed Days',shortTitle:'Public Holidays NZ',description:'National and regional public holidays, observed dates and holiday-pay guidance with date-aware status.',category:'Holidays & family',searchTerms:['public holidays nz','public holidays nz 2026','public holidays nz 2027','nz public holidays','nz holiday dates','auckland anniversary day'],fresh:'Date-aware current status',related:['/school-holidays-nz','/nz-holiday-pay-calculator','/nz-leave-entitlement-calculator','/nz-guides']},
{href:'/school-holidays-nz',title:'School Holidays NZ 2026 & 2027 — Term Dates & Next Break',shortTitle:'School Holidays NZ',description:'Check the next school holidays plus official 2026 and 2027 New Zealand term and holiday dates with live status.',category:'Holidays & family',searchTerms:['school holidays nz','nz school holidays 2026','nz school holidays 2027','school term dates nz','next school holidays nz'],fresh:'Date-aware Ministry calendar',related:['/public-holidays','/nz-leave-entitlement-calculator','/nz-guides']},
{href:'/immigration',title:'New Zealand Immigration & Visa Guide 2026',shortTitle:'NZ Immigration & Visa Guide',description:'Compare work, student, visitor, residence and family visa pathways with direct Immigration New Zealand sources.',category:'Immigration & citizenship',searchTerms:['new zealand immigration','immigration nz','new zealand visa','nz visa','work visa nz','student visa nz'],fresh:'Live visa-source monitoring',related:['/visitor-visa-nz','/nz-citizenship','/jobs-in-new-zealand','/new-zealand-passport-application']},
{href:'/visitor-visa-nz',title:'New Zealand Visitor Visa 2026 — Cost, Time & Requirements',shortTitle:'New Zealand Visitor Visa',description:'Current Visitor Visa cost from $441, processing time, stay length, requirements and official online application link.',category:'Immigration & citizenship',searchTerms:['new zealand visitor visa','visitor visa nz','nz visitor visa','new zealand tourist visa','nz visitor visa requirements','nz visitor visa cost'],fresh:'Frequent Immigration NZ source checks',related:['/immigration','/nz-citizenship','/jobs-in-new-zealand','/new-zealand-passport-application']},
{href:'/nz-citizenship',title:'NZ Citizenship 2026 — Check Eligibility, 5-Year Rule & Fees',shortTitle:'NZ Citizenship',description:'Check citizenship-by-grant eligibility, 1,350-day and 240-day presence rules, fees, application steps and requirements.',category:'Immigration & citizenship',searchTerms:['nz citizenship','new zealand citizenship','nz citizenship application','nz citizenship eligibility','nz citizenship 5 year rule','nz citizenship fee 2026'],fresh:'Daily NZ Government source checks',related:['/immigration','/new-zealand-passport-application','/nz-passport-renewal','/nz-superannuation']},
{href:'/new-zealand-passport-application',title:'NZ Passport Application 2026 — Cost, Time & Apply Online',shortTitle:'NZ Passport Application',description:'Apply for a New Zealand passport with current adult and child fees, processing times, requirements and official online link.',category:'Immigration & citizenship',searchTerms:['nz passport application','new zealand passport application','apply for nz passport','nz passport cost','nz passport processing time','first nz passport'],fresh:'Regular NZ Passports source checks',related:['/nz-passport-renewal','/nz-citizenship','/immigration','/visitor-visa-nz']},
{href:'/nz-passport-renewal',title:'NZ Passport Renewal 2026 — Cost, Processing Time & Online Renewal',shortTitle:'NZ Passport Renewal',description:'Check passport renewal cost, standard and urgent processing times, photo rules, referee requirements and online renewal guidance.',category:'Immigration & citizenship',searchTerms:['nz passport renewal','new zealand passport renewal','renew nz passport','nz passport renewal cost','nz passport processing time','nz passport renewal online'],fresh:'Regular NZ Passports source checks',related:['/new-zealand-passport-application','/nz-citizenship','/immigration','/visitor-visa-nz']},
{href:'/jobs-in-new-zealand',title:'Jobs in New Zealand 2026 — Job Sites, Entry-Level & Visa Jobs',shortTitle:'Jobs in New Zealand',description:'Find New Zealand job sites, part-time and no-experience roles, remote work, government jobs and accredited-employer pathways.',category:'Jobs & careers',searchTerms:['jobs in new zealand','jobs nz','new zealand jobs','part time jobs nz','no experience jobs nz','visa sponsorship jobs nz','accredited employer jobs nz'],fresh:'Regular official job-source checks',related:['/government-jobs-nz','/immigration','/minimum-wage','/nz-paye-calculator']},
{href:'/government-jobs-nz',title:'Government Jobs NZ 2026 — Current Public Service Vacancies',shortTitle:'Government Jobs NZ',description:'Search current NZ government vacancies, locations, career categories, graduate programmes and official jobs.govt.nz links.',category:'Jobs & careers',searchTerms:['government jobs nz','nz government jobs','government vacancies nz','public service jobs nz','jobs govt nz','government jobs auckland'],fresh:'Frequent vacancy checks',related:['/jobs-in-new-zealand','/minimum-wage','/nz-paye-calculator','/immigration']},
];
export function getNzGuide(href:string){return nzGuides.find(guide=>guide.href===href);}
export function getRelatedNzGuides(href:string,limit=4){const guide=getNzGuide(href);if(!guide)return [];return guide.related.map(path=>getNzGuide(path)).filter((item):item is NzGuideEntry=>Boolean(item)&&item!.href!==href).slice(0,limit);}
