'use client';
import { useState } from 'react';

export default function AdManager({campaigns,slots,creatives,assignments,media}:{campaigns:any[];slots:any[];creatives:any[];assignments:any[];media:any[]}){
 const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');
 async function post(path:string,body:any){setBusy(true);setMsg('');const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setMsg(j.error||'Could not save');return false;}location.reload();return true;}
 async function createCampaign(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);await post('/api/admin/ads',{advertiser_name:fd.get('advertiser_name'),campaign_name:fd.get('campaign_name'),status:fd.get('status'),starts_at:fd.get('starts_at')||null,ends_at:fd.get('ends_at')||null,notes:fd.get('notes')||null});}
 async function createCreative(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);await post('/api/admin/ads/creative',{campaign_id:fd.get('campaign_id'),media_id:fd.get('media_id')||null,headline:fd.get('headline')||null,destination_url:fd.get('destination_url'),alt_text:fd.get('alt_text')||null});}
 async function createAssignment(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);await post('/api/admin/ads/assignment',{slot_id:fd.get('slot_id'),creative_id:fd.get('creative_id'),starts_at:fd.get('starts_at')||null,ends_at:fd.get('ends_at')||null,priority:Number(fd.get('priority')||100),is_active:true});}
 async function status(id:string,status:string){setBusy(true);const r=await fetch('/api/admin/ads/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});setBusy(false);if(r.ok)location.reload();else setMsg('Could not update campaign');}
 return <div className="ads-console">
  {msg?<div className="admin-alert">{msg}</div>:null}
  <div className="admin-metrics ad-metrics"><div><span>Campaigns</span><strong>{campaigns.length}</strong></div><div><span>Creatives</span><strong>{creatives.length}</strong></div><div><span>Live placements</span><strong>{assignments.filter(a=>a.is_active).length}</strong></div><div><span>Ad positions</span><strong>{slots.length}</strong></div></div>
  <div className="ad-workflow-grid">
   <section className="admin-card"><div className="admin-card-title"><span>01</span><div><h2>Create campaign</h2><p>Set the advertiser, dates and commercial status.</p></div></div><form className="admin-form-grid" onSubmit={createCampaign}><label>Advertiser<input name="advertiser_name" required/></label><label>Campaign name<input name="campaign_name" required/></label><label>Status<select name="status" defaultValue="draft"><option>draft</option><option>active</option><option>paused</option><option>ended</option></select></label><label>Starts<input name="starts_at" type="datetime-local"/></label><label>Ends<input name="ends_at" type="datetime-local"/></label><label className="admin-span-2">Notes<textarea name="notes" rows={3}/></label><div><button className="admin-primary" disabled={busy}>Create campaign</button></div></form></section>
   <section className="admin-card"><div className="admin-card-title"><span>02</span><div><h2>Add creative</h2><p>Select artwork already uploaded to Media and add the click destination.</p></div></div><form className="admin-form-grid" onSubmit={createCreative}><label>Campaign<select name="campaign_id" required><option value="">Choose campaign</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.campaign_name}</option>)}</select></label><label>Artwork<select name="media_id" required><option value="">Choose image</option>{media.map(m=><option key={m.id} value={m.id}>{m.filename}</option>)}</select></label><label className="admin-span-2">Headline<input name="headline"/></label><label className="admin-span-2">Destination URL<input name="destination_url" type="url" required placeholder="https://advertiser.co.nz/"/></label><label className="admin-span-2">Alt text<input name="alt_text"/></label><div><button className="admin-primary" disabled={busy||!campaigns.length}>Save creative</button></div></form></section>
   <section className="admin-card"><div className="admin-card-title"><span>03</span><div><h2>Place advertisement</h2><p>Assign a creative to a named position on the website.</p></div></div><form className="admin-form-grid" onSubmit={createAssignment}><label>Ad position<select name="slot_id" required><option value="">Choose position</option>{slots.map(s=><option key={s.id} value={s.id}>{s.label} ({s.key})</option>)}</select></label><label>Creative<select name="creative_id" required><option value="">Choose creative</option>{creatives.map(c=><option key={c.id} value={c.id}>{c.headline||c.id.slice(0,8)}</option>)}</select></label><label>Starts<input name="starts_at" type="datetime-local"/></label><label>Ends<input name="ends_at" type="datetime-local"/></label><label>Priority<input name="priority" type="number" defaultValue="100" min="0" max="1000"/></label><div><button className="admin-primary" disabled={busy||!creatives.length}>Publish placement</button></div></form></section>
  </div>
  <section className="admin-card"><div className="admin-card-head"><h2>Campaigns</h2><span className="admin-note">Campaign status controls commercial workflow.</span></div>{campaigns.length?<div className="admin-table-wrap"><table><thead><tr><th>Advertiser</th><th>Campaign</th><th>Status</th><th>Dates</th><th>Action</th></tr></thead><tbody>{campaigns.map(c=><tr key={c.id}><td>{c.advertiser_name}</td><td>{c.campaign_name}</td><td><span className={`status-badge status-${c.status}`}>{c.status}</span></td><td>{c.starts_at?new Date(c.starts_at).toLocaleDateString('en-NZ'):'Open'} to {c.ends_at?new Date(c.ends_at).toLocaleDateString('en-NZ'):'Open'}</td><td><select defaultValue={c.status} onChange={e=>status(c.id,e.target.value)} disabled={busy}><option>draft</option><option>active</option><option>paused</option><option>ended</option></select></td></tr>)}</tbody></table></div>:<div className="admin-empty">No campaigns yet. Start with step 01 above.</div>}</section>
  <section className="admin-card"><div className="admin-card-head"><h2>Advertising inventory</h2><span className="admin-note">These positions are available across desktop and mobile layouts.</span></div><div className="ad-slot-grid">{slots.map(s=><div key={s.id}><strong>{s.label}</strong><code>{s.key}</code><span>{s.recommended_width||'?'} × {s.recommended_height||'?'}</span><small>{s.description}</small></div>)}</div></section>
 </div>;
}
