import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import PdfToolbox from '../../ilikepdf/PdfToolbox';
import styles from '../../ilikepdf/ilikepdf.module.css';

const SITE='https://webfitnews.com';
const toolPages={
  'pdf-to-jpg':{id:'pdf-jpg',title:'PDF to JPG Converter Free Online',h1:'Convert PDF to JPG online for free',description:'Convert PDF pages to high-quality JPG images online for free with ILikeMyPdf. No account required and files are processed in your browser.',intro:'Turn every page of a PDF into a JPG image. ILikeMyPdf renders your PDF in the browser and downloads the converted pages together in a ZIP file.',steps:['Choose your PDF file.','ILikeMyPdf converts each PDF page to JPG.','Download the JPG images in one ZIP file.'],faq:['The PDF to JPG converter is free to use.','Your source PDF is processed locally in your browser.']},
  'jpg-to-pdf':{id:'image-pdf',title:'JPG to PDF Converter Free Online',h1:'Convert JPG to PDF online for free',description:'Convert JPG images to PDF online for free. Combine one or multiple JPG files into a PDF with ILikeMyPdf, with browser-based processing.',intro:'Create one PDF from one or more JPG or PNG images. Each selected image becomes a page in the finished PDF.',steps:['Choose one or more JPG or PNG images.','The images are placed into a PDF in your selected order.','Download the finished PDF.'],faq:['You can combine multiple images into one PDF.','JPG and PNG images are supported.']},
  'pdf-to-word':{id:'pdf-word',title:'PDF to Word Converter Free Online',h1:'Convert PDF to Word online for free',description:'Convert text-based PDF files to editable Word DOCX files online for free with ILikeMyPdf. Browser-based conversion with no account required.',intro:'Extract readable text from a PDF and create an editable Word DOCX document. This tool works best with text-based PDFs.',steps:['Choose a text-based PDF.','ILikeMyPdf extracts readable text from each page.','Download the generated Word DOCX file.'],faq:['Text-based PDFs work best.','Complex layouts, scanned pages, forms and tables can require cleanup.']},
  'word-to-pdf':{id:'word-pdf',title:'Word to PDF Converter Free Online',h1:'Convert Word to PDF online for free',description:'Convert DOCX Word documents to PDF online for free with ILikeMyPdf. No account required and document processing happens in your browser.',intro:'Turn the readable text in a DOCX Word document into a clean PDF without creating an account.',steps:['Choose a DOCX Word document.','ILikeMyPdf reads the document text.','Download the generated PDF.'],faq:['The converter supports DOCX files.','Complex Word layouts may not reproduce exactly because conversion is text-oriented.']},
  'merge-pdf':{id:'merge',title:'Merge PDF Files Free Online',h1:'Merge PDF files online for free',description:'Merge multiple PDF files into one PDF online for free with ILikeMyPdf. Combine PDFs in your browser without creating an account.',intro:'Combine multiple PDF documents into a single PDF while keeping the pages in file order.',steps:['Choose two or more PDF files.','ILikeMyPdf copies their pages into one document.','Download the merged PDF.'],faq:['You can merge multiple PDF files in one operation.','Source files are processed in your browser.']},
  'split-pdf':{id:'split',title:'Split PDF Free Online',h1:'Split PDF pages online for free',description:'Split a PDF and extract selected pages online for free with ILikeMyPdf. Choose page ranges and download a new PDF in your browser.',intro:'Keep only the pages you need by entering page numbers or ranges such as 1-3,5.',steps:['Choose a PDF file.','Enter the pages or ranges you want to keep.','Download the new split PDF.'],faq:['Page ranges such as 1-3,5 are supported.','The original PDF is not modified.']},
  'compress-pdf':{id:'compress',title:'Compress PDF Free Online',h1:'Compress PDF files online for free',description:'Compress image-heavy PDF files online for free with ILikeMyPdf. Reduce PDF size directly in your browser without an account.',intro:'Reduce the size of image-heavy PDFs by rendering and rebuilding their pages with compressed images.',steps:['Choose a PDF file.','ILikeMyPdf compresses and rebuilds its pages.','Download the compressed PDF.'],faq:['This method is most useful for image-heavy PDFs.','Compression can flatten searchable text, forms and links.']},
  'pdf-to-png':{id:'pdf-png',title:'PDF to PNG Converter Free Online',h1:'Convert PDF to PNG online for free',description:'Convert PDF pages to PNG images online for free with ILikeMyPdf. Browser-based PDF to PNG conversion with no account required.',intro:'Export each PDF page as a PNG image and download all converted pages together in a ZIP file.',steps:['Choose your PDF file.','Each page is rendered as a PNG image.','Download all PNG pages in a ZIP file.'],faq:['Every PDF page is converted to PNG.','Processing happens in your browser.']},
  'rotate-pdf':{id:'rotate',title:'Rotate PDF Free Online',h1:'Rotate PDF pages online for free',description:'Rotate PDF pages 90, 180 or 270 degrees online for free with ILikeMyPdf. Process and download the rotated PDF in your browser.',intro:'Fix sideways or upside-down PDFs by rotating every page clockwise by 90, 180 or 270 degrees.',steps:['Choose a PDF file.','Select the rotation angle.','Download the rotated PDF.'],faq:['You can rotate by 90, 180 or 270 degrees.','The tool rotates every page in the selected PDF.']},
  'watermark-pdf':{id:'watermark',title:'Watermark PDF Free Online',h1:'Add a watermark to PDF online for free',description:'Add a text watermark to PDF pages online for free with ILikeMyPdf. Create a watermarked PDF directly in your browser.',intro:'Add visible text across every page of a PDF for draft, review or document-identification purposes.',steps:['Choose a PDF file.','Enter the watermark text.','Download the watermarked PDF.'],faq:['The watermark is applied across every page.','The source PDF is processed in your browser.']},
} as const;

type Slug=keyof typeof toolPages;
export function generateStaticParams(){return Object.keys(toolPages).map(tool=>({tool}));}
export async function generateMetadata({params}:{params:Promise<{tool:string}>}):Promise<Metadata>{const {tool}=await params;const item=toolPages[tool as Slug];if(!item)return{};const canonical=`/ilikemypdf/${tool}`;return{title:`${item.title} | ILikeMyPdf`,description:item.description,alternates:{canonical},robots:{index:true,follow:true},openGraph:{title:item.title,description:item.description,url:canonical,type:'website'}};}

export default async function ToolSeoPage({params}:{params:Promise<{tool:string}>}){const {tool}=await params;const item=toolPages[tool as Slug];if(!item)notFound();const url=`${SITE}/ilikemypdf/${tool}`;const schema={'@context':'https://schema.org','@type':'WebApplication',name:item.title,applicationCategory:'UtilitiesApplication',operatingSystem:'Any modern web browser',url,description:item.description,offers:{'@type':'Offer',price:'0',priceCurrency:'NZD'}};const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:`${SITE}/`},{'@type':'ListItem',position:2,name:'ILikeMyPdf',item:`${SITE}/ilikemypdf`},{'@type':'ListItem',position:3,name:item.h1,item:url}]};return <main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/><nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/ilikemypdf">ILikeMyPdf</Link><span>/</span><span>{item.h1}</span></nav><header className={styles.hero}><p className={styles.brand}>ILikeMyPdf • FREE ONLINE PDF TOOL</p><h1>{item.h1}</h1><p>{item.description}</p><div className={styles.heroBadges}><span>Free to use</span><span>No account required</span><span>Browser processing</span><span>Mobile friendly</span></div></header><PdfToolbox initialTool={item.id}/><section className={styles.section}><h2>How to {item.h1.toLowerCase().replace(' online for free','')}</h2><p className={styles.sectionLead}>{item.intro}</p><div className={styles.featureGrid}>{item.steps.map((step,i)=><article className={styles.featureCard} key={step}><h3>Step {i+1}</h3><p>{step}</p></article>)}</div></section><section className={styles.section}><h2>Why use ILikeMyPdf?</h2><p className={styles.sectionLead}>ILikeMyPdf is a free Webfit News utility designed for quick everyday PDF jobs. The tools on this page run in your browser, so your source document does not need to be uploaded to a remote conversion queue.</p></section><section className={styles.section}><h2>{item.h1.replace('online for free','')} FAQ</h2><div className={styles.faq}>{item.faq.map((answer,i)=><details key={answer}><summary>{i===0?'Is this tool free?':'What should I know before converting?'}</summary><p>{answer}</p></details>)}</div><p className={styles.sectionLead}>Need another document task? <Link href="/ilikemypdf">Browse all free ILikeMyPdf PDF tools</Link>.</p></section></main>}
