import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import PdfToolbox from '../../ilikepdf/PdfToolbox';
import styles from '../../ilikepdf/ilikepdf.module.css';

const SITE='https://webfitnews.com';
const toolPages={
'pdf-to-jpg':{title:'PDF to JPG Converter Free Online',h1:'Convert PDF to JPG online for free',description:'Convert PDF pages to high-quality JPG images online for free with ILikeMyPdf. No account required and files are processed in your browser.',intro:'Turn every page of a PDF into a JPG image. ILikeMyPdf renders your PDF in the browser and downloads the converted pages together in a ZIP file.',steps:['Choose PDF to JPG in the tool box and select your PDF.','ILikeMyPdf converts each PDF page to JPG.','Download the JPG images in one ZIP file.'],faq:['The PDF to JPG converter is free to use.','Your source PDF is processed locally in your browser.']},
'jpg-to-pdf':{title:'JPG to PDF Converter Free Online',h1:'Convert JPG to PDF online for free',description:'Convert JPG images to PDF online for free. Combine one or multiple JPG files into a PDF with ILikeMyPdf, with browser-based processing.',intro:'Create one PDF from one or more JPG or PNG images. Each selected image becomes a page in the finished PDF.',steps:['Choose JPG / PNG to PDF and select one or more images.','The images are placed into a PDF in your selected order.','Download the finished PDF.'],faq:['You can combine multiple images into one PDF.','JPG and PNG images are supported.']},
'pdf-to-word':{title:'PDF to Word Converter Free Online',h1:'Convert PDF to Word online for free',description:'Convert text-based PDF files to editable Word DOCX files online for free with ILikeMyPdf. Browser-based conversion with no account required.',intro:'Extract readable text from a PDF and create an editable Word DOCX document. This tool works best with text-based PDFs.',steps:['Choose PDF to Word and select a text-based PDF.','ILikeMyPdf extracts readable text from each page.','Download the generated Word DOCX file.'],faq:['Text-based PDFs work best.','Complex layouts, scanned pages, forms and tables can require cleanup.']},
'word-to-pdf':{title:'Word to PDF Converter Free Online',h1:'Convert Word to PDF online for free',description:'Convert DOCX Word documents to PDF online for free with ILikeMyPdf. No account required and document processing happens in your browser.',intro:'Turn the readable text in a DOCX Word document into a clean PDF without creating an account.',steps:['Choose Word to PDF and select a DOCX document.','ILikeMyPdf reads the document text.','Download the generated PDF.'],faq:['The converter supports DOCX files.','Complex Word layouts may not reproduce exactly because conversion is text-oriented.']},
'merge-pdf':{title:'Merge PDF Files Free Online',h1:'Merge PDF files online for free',description:'Merge multiple PDF files into one PDF online for free with ILikeMyPdf. Combine PDFs in your browser without creating an account.',intro:'Combine multiple PDF documents into a single PDF while keeping the pages in file order.',steps:['Choose Merge PDF and select two or more PDF files.','ILikeMyPdf copies their pages into one document.','Download the merged PDF.'],faq:['You can merge multiple PDF files in one operation.','Source files are processed in your browser.']},
'split-pdf':{title:'Split PDF Free Online',h1:'Split PDF pages online for free',description:'Split a PDF and extract selected pages online for free with ILikeMyPdf. Choose page ranges and download a new PDF in your browser.',intro:'Keep only the pages you need by entering page numbers or ranges such as 1-3,5.',steps:['Choose Split PDF and select a PDF file.','Enter the pages or ranges you want to keep.','Download the new split PDF.'],faq:['Page ranges such as 1-3,5 are supported.','The original PDF is not modified.']},
'compress-pdf':{title:'Compress PDF Free Online',h1:'Compress PDF files online for free',description:'Compress image-heavy PDF files online for free with ILikeMyPdf. Reduce PDF size directly in your browser without an account.',intro:'Reduce the size of image-heavy PDFs by rendering and rebuilding their pages with compressed images.',steps:['Choose Compress PDF and select a PDF file.','ILikeMyPdf compresses and rebuilds its pages.','Download the compressed PDF.'],faq:['This method is most useful for image-heavy PDFs.','Compression can flatten searchable text, forms and links.']},
'pdf-to-png':{title:'PDF to PNG Converter Free Online',h1:'Convert PDF to PNG online for free',description:'Convert PDF pages to PNG images online for free with ILikeMyPdf. Browser-based PDF to PNG conversion with no account required.',intro:'Export each PDF page as a PNG image and download all converted pages together in a ZIP file.',steps:['Choose PDF to PNG and select your PDF.','Each page is rendered as a PNG image.','Download all PNG pages in a ZIP file.'],faq:['Every PDF page is converted to PNG.','Processing happens in your browser.']},
'rotate-pdf':{title:'Rotate PDF Free Online',h1:'Rotate PDF pages online for free',description:'Rotate PDF pages 90, 180 or 270 degrees online for free with ILikeMyPdf. Process and download the rotated PDF in your browser.',intro:'Fix sideways or upside-down PDFs by rotating every page clockwise by 90, 180 or 270 degrees.',steps:['Choose Rotate PDF and select a PDF file.','Select the rotation angle.','Download the rotated PDF.'],faq:['You can rotate by 90, 180 or 270 degrees.','The tool rotates every page in the selected PDF.']},
'watermark-pdf':{title:'Watermark PDF Free Online',h1:'Add a watermark to PDF online for free',description:'Add a text watermark to PDF pages online for free with ILikeMyPdf. Create a watermarked PDF directly in your browser.',intro:'Add visible text across every page of a PDF for draft, review or document-identification purposes.',steps:['Choose Watermark PDF and select a PDF file.','Enter the watermark text.','Download the watermarked PDF.'],faq:['The watermark is applied across every page.','The source PDF is processed in your browser.']},
'png-to-pdf':{title:'PNG to PDF Converter Free Online',h1:'Convert PNG to PDF online for free',description:'Convert PNG images to PDF online for free with ILikeMyPdf. Combine one or multiple PNG files into a PDF directly in your browser.',intro:'Turn one or more PNG images into a PDF. Each selected image becomes its own page in the finished document.',steps:['Choose JPG / PNG to PDF and select one or more PNG images.','Keep the images in the order you want them to appear.','Download the finished PDF.'],faq:['PNG images are supported by the JPG / PNG to PDF tool.','You can combine multiple PNG files into one PDF.']},
'pdf-to-text':{title:'PDF to Text Converter Free Online',h1:'Convert PDF to text online for free',description:'Extract readable text from text-based PDF files online for free with ILikeMyPdf. Browser-based PDF to text conversion with no account required.',intro:'Extract plain text from a text-based PDF so you can copy, edit or reuse the document content.',steps:['Choose PDF to Text and select a text-based PDF.','ILikeMyPdf extracts readable text from each page.','Download or copy the resulting text.'],faq:['This works best with text-based PDFs.','Scanned image-only PDFs need OCR, which is not included in this tool.']},
'word-to-jpg':{title:'Word to JPG Converter Free Online',h1:'Convert Word to JPG online for free',description:'Convert DOCX Word document content to JPG images online for free with ILikeMyPdf. Browser-based processing with no account required.',intro:'Convert readable content from a DOCX Word document into JPG image output for quick sharing or previewing.',steps:['Choose Word to JPG and select a DOCX document.','ILikeMyPdf reads the document content in your browser.','Download the generated JPG image output.'],faq:['The converter supports DOCX files.','Complex Word formatting may not reproduce exactly because conversion is text-oriented.']},
'remove-pdf-pages':{title:'Remove PDF Pages Free Online',h1:'Remove pages from PDF online for free',description:'Remove unwanted pages from a PDF online for free with ILikeMyPdf. Keep only the pages you need and download a new PDF in your browser.',intro:'Delete unwanted pages from a PDF without modifying your original file.',steps:['Choose Remove PDF Pages and select a PDF file.','Enter or select the pages you want removed.','Download the new PDF with those pages removed.'],faq:['The original PDF remains unchanged.','You can remove one or multiple pages in a single operation.']},
'organize-pdf-pages':{title:'Organize PDF Pages Free Online',h1:'Organize PDF pages online for free',description:'Reorder PDF pages online for free with ILikeMyPdf. Arrange pages into a new sequence and download the reorganized PDF in your browser.',intro:'Rearrange the order of PDF pages by specifying the sequence you want in the finished document.',steps:['Choose Organize PDF and select a PDF file.','Enter the page order you want, such as 3,1,2.','Download the reorganized PDF.'],faq:['You can place pages into a custom sequence.','The original PDF is not modified.']},
'add-page-numbers-to-pdf':{title:'Add Page Numbers to PDF Free Online',h1:'Add page numbers to PDF online for free',description:'Add page numbers to PDF pages online for free with ILikeMyPdf. Number your document and download the updated PDF directly in your browser.',intro:'Add simple page numbers to every page of a PDF for easier reading, printing and reference.',steps:['Choose Add Page Numbers and select a PDF file.','ILikeMyPdf adds page numbers to the document.','Download the numbered PDF.'],faq:['Page numbers are added across the PDF.','Your source file is processed in your browser.']},
'text-to-pdf':{title:'Text to PDF Converter Free Online',h1:'Convert text to PDF online for free',description:'Convert pasted text into a PDF online for free with ILikeMyPdf. Create a simple PDF document directly in your browser with no account required.',intro:'Turn plain text into a simple PDF document for downloading, printing or sharing.',steps:['Choose Text to PDF.','Paste or type the text you want in the document.','Create and download the PDF.'],faq:['This tool is designed for plain text content.','No source document upload is required when you paste text directly.']},
} as const;
type Slug=keyof typeof toolPages;
export function generateStaticParams(){return Object.keys(toolPages).map(tool=>({tool}));}
export async function generateMetadata({params}:{params:Promise<{tool:string}>}):Promise<Metadata>{const {tool}=await params;const item=toolPages[tool as Slug];if(!item)return{};const canonical=`/ilikemypdf/${tool}`;return{title:`${item.title} | ILikeMyPdf`,description:item.description,alternates:{canonical},robots:{index:true,follow:true},openGraph:{title:item.title,description:item.description,url:canonical,type:'website'}};}
export default async function ToolSeoPage({params}:{params:Promise<{tool:string}>}){const {tool}=await params;const item=toolPages[tool as Slug];if(!item)notFound();const url=`${SITE}/ilikemypdf/${tool}`;const schema={'@context':'https://schema.org','@type':'WebApplication',name:item.title,applicationCategory:'UtilitiesApplication',operatingSystem:'Any modern web browser',url,description:item.description,offers:{'@type':'Offer',price:'0',priceCurrency:'NZD'}};const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:`${SITE}/`},{'@type':'ListItem',position:2,name:'ILikeMyPdf',item:`${SITE}/ilikemypdf`},{'@type':'ListItem',position:3,name:item.h1,item:url}]};return <main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/><nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/ilikemypdf">ILikeMyPdf</Link><span>/</span><span>{item.h1}</span></nav><header className={styles.hero}><p className={styles.brand}>ILikeMyPdf • FREE ONLINE PDF TOOL</p><h1>{item.h1}</h1><p>{item.description}</p><div className={styles.heroBadges}><span>Free to use</span><span>No account required</span><span>Browser processing</span><span>Mobile friendly</span></div></header><PdfToolbox/><section className={styles.section}><h2>How to {item.h1.toLowerCase().replace(' online for free','')}</h2><p className={styles.sectionLead}>{item.intro}</p><div className={styles.featureGrid}>{item.steps.map((step,i)=><article className={styles.featureCard} key={step}><h3>Step {i+1}</h3><p>{step}</p></article>)}</div></section><section className={styles.section}><h2>Why use ILikeMyPdf?</h2><p className={styles.sectionLead}>ILikeMyPdf is a free Webfit News utility designed for quick everyday PDF jobs. The tools on this page run in your browser, so your source document does not need to be uploaded to a remote conversion queue.</p></section><section className={styles.section}><h2>{item.h1.replace('online for free','')} FAQ</h2><div className={styles.faq}>{item.faq.map((answer,i)=><details key={answer}><summary>{i===0?'Is this tool free?':'What should I know before converting?'}</summary><p>{answer}</p></details>)}</div><p className={styles.sectionLead}>Need another document task? <Link href="/ilikemypdf">Browse all free ILikeMyPdf PDF tools</Link>.</p></section></main>}
