import type {Metadata} from 'next';
import Link from 'next/link';
import {SiteHeader} from '@/components/SiteHeader';
import {PublicFooter} from '@/components/PublicFooter';
import styles from '@/components/UtilityGuide.module.css';
import {NZ_GUIDE_SITE_URL,nzGuideCategories,nzGuides} from '@/lib/nz-guide-catalog';

export const metadata:Metadata={
  title:'New Zealand Calculators & Guides 2026 | Tax, Pay, Visas & Holidays',
  description:'Free New Zealand calculators and practical 2026 guides for PAYE, wages, ACC, KiwiSaver, rates rebates, tenancy, holidays, visas, passports and jobs, with official NZ sources.',
  alternates:{canonical:'/nz-guides'},
  robots:{index:true,follow:true},
  openGraph:{title:'New Zealand Calculators & Guides 2026 | Webfit News',description:'Practical NZ calculators and guides for money, work, housing, immigration, holidays and jobs, built around official government sources.',url:'/nz-guides',type:'website'},
  twitter:{card:'summary_large_image',title:'New Zealand Calculators & Guides 2026 | Webfit News',description:'Practical NZ calculators and guides for money, work, housing, immigration, holidays and jobs.'},
};

export default function NzGuidesPage(){
  const itemList=nzGuides.map((guide,index)=>({'@type':'ListItem',position:index+1,name:guide.title,url:`${NZ_GUIDE_SITE_URL}${guide.href}`}));
  const structuredData={'@context':'https://schema.org','@graph':[
    {'@type':'CollectionPage',name:'New Zealand Calculators and Guides 2026',url:`${NZ_GUIDE_SITE_URL}/nz-guides`,description:metadata.description,isPartOf:{'@type':'WebSite',name:'Webfit News',url:NZ_GUIDE_SITE_URL},about:[{'@type':'Thing',name:'New Zealand tax and personal finance'},{'@type':'Thing',name:'New Zealand employment rights'},{'@type':'Thing',name:'New Zealand immigration and citizenship'},{'@type':'Thing',name:'New Zealand housing and household costs'},{'@type':'Thing',name:'New Zealand public and school holidays'}]},
    {'@type':'ItemList',name:'Webfit News New Zealand Guides',itemListElement:itemList},
    {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Webfit News',item:NZ_GUIDE_SITE_URL},{'@type':'ListItem',position:2,name:'New Zealand Guides',item:`${NZ_GUIDE_SITE_URL}/nz-guides`}]},
  ]};
  return <><SiteHeader/><main className={`shell ${styles.page}`}>
    <section className={styles.hero}><div><span className={styles.eyebrow}>Webfit News NZ Guides</span><h1>New Zealand calculators & guides 2026</h1><p className={styles.lead}>Find practical New Zealand calculators and guides for tax, wages, ACC, KiwiSaver, leave, rates, tenancy, immigration, citizenship, passports, holidays and jobs. Each page explains the topic clearly and links to the relevant official New Zealand source where appropriate.</p></div><div className={styles.heroCard}><span>NZ utility library</span><strong>{nzGuides.length} live guides</strong><small>Useful calculators and guides grouped by topic, with related information easy to find.</small></div></section>
    <nav className={styles.jumpNav} aria-label="New Zealand guide categories"><span>Browse:</span>{nzGuideCategories.map(category=><a key={category} href={`#${category.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`}>{category}</a>)}</nav>
    <section className={styles.section}><div className={styles.sectionHeading}><span className={styles.kicker}>Popular guides</span><h2>Start with popular New Zealand calculators and guides</h2><p>Quickly check take-home pay, minimum wage, rates rebates, public holidays, immigration information and citizenship guidance. Each page is designed to give you a useful answer and point you to the official source when you need to confirm a detail.</p></div><div className={styles.infoGrid}>{['/nz-paye-calculator','/minimum-wage','/nz-rates-rebate-calculator','/public-holidays','/immigration','/nz-citizenship'].map(href=>{const guide=nzGuides.find(item=>item.href===href)!;return <article key={guide.href}><h3><Link href={guide.href}>{guide.title}</Link></h3><p>{guide.description}</p><div className={styles.metaRow}><span>{guide.fresh}</span></div><Link className={styles.cta} href={guide.href}>Open {guide.shortTitle} →</Link></article>})}</div></section>
    {nzGuideCategories.map(category=>{const guides=nzGuides.filter(guide=>guide.category===category);const id=category.toLowerCase().replace(/[^a-z0-9]+/g,'-');return <section id={id} className={styles.section} key={category}><div className={styles.sectionHeading}><span className={styles.kicker}>NZ Guides</span><h2>{category}</h2><p>{category==='Money & tax'?'New Zealand tax, PAYE, ACC, KiwiSaver, student-loan, retirement and rebate tools.':category==='Work & employment'?'New Zealand wage, holiday-pay, sick-leave and annual-leave guidance.':category==='Housing & household costs'?'New Zealand rates-rebate, tenancy, rent-increase, bond and household-cost guidance.':category==='Immigration & citizenship'?'New Zealand visa, immigration, citizenship and passport guides with official application links.':category==='Holidays & family'?'Current New Zealand public-holiday and school-holiday dates with practical leave guidance.':'New Zealand job-search and Public Service vacancy guidance.'}</p></div><div className={styles.infoGrid}>{guides.map(guide=><article key={guide.href}><h3><Link href={guide.href}>{guide.title}</Link></h3><p>{guide.description}</p><div className={styles.metaRow}><span>{guide.fresh}</span></div><Link className={styles.cta} href={guide.href}>Open {guide.shortTitle} →</Link></article>)}</div></section>})}
    <section className={styles.section}><div className={styles.sectionHeading}><span className={styles.kicker}>About these guides</span><h2>Clear information backed by official New Zealand sources</h2><p>Webfit News turns public information into practical calculators, tables, checklists and plain-language guides. Important rates, dates, eligibility rules and application requirements should always be confirmed with the government agency linked from the relevant page.</p></div></section>
    <aside className={styles.disclaimer}><strong>Source policy:</strong> Webfit News reorganises official New Zealand public information for readability and practical use. Always confirm important decisions on the linked government website.</aside>
  </main><PublicFooter/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,'\\u003c')}}/></>;
}
